### ISSUE TITLE
Error occur in POST /session

### ISSUE THREAD

**Issue by ttochi** [SeaJungg/rloging#15]
session 생성 API 호출 시 attendee(신청자수) 필드와 관련하여 에러가 발생합니다 😭 
백엔드에서 default 값을 받도록 처리가 필요할 것 같습니다.

아래는 local에서 `http://localhost:8000/api/v1/session/`을 동작시킨 화면입니다.

1. session 생성을 위한 필드값을 입력하여 post 요청을 보내면 attendee(신청자수)가 required field라고 뜸
<img width="611" alt="1" src="https://user-images.githubusercontent.com/12132672/211198287-1cd13c7f-89ed-4f0e-aa4a-2622d4bdd326.png">
<img width="556" alt="2" src="https://user-images.githubusercontent.com/12132672/211198289-8340f649-df5c-49df-8f60-967d66567233.png">

2. attendee를 empty array로 보냈을 때 아래와 같은 에러가 발생
<img width="576" alt="3" src="https://user-images.githubusercontent.com/12132672/211198290-026dac51-69d2-4dd9-bafb-2db78d0b4e10.png">
<img width="752" alt="4" src="https://user-images.githubusercontent.com/12132672/211198208-a066638a-9afc-4179-a844-e8313129ae50.png">

**Comment by SeaJungg** [comment]
https://github.com/SeaJungg/rloging/pull/17 에서 해결하였습니다 :) 히히
